const Joi = require('joi');
const common_field = {
  id: Joi.number().integer().positive(),
  deviceId: Joi.string().required(),
  status: Joi.string().max(50),
  description: Joi.string().max(1000),
  location: Joi.string(),
  name: Joi.string(),
  imageUrl: Joi.string().max(1000),
  imei: Joi.string(),
  imsi: Joi.string(),
  cellProvider: Joi.string(),
  phoneNumber: Joi.string().max(20),
  batteryVoltage: Joi.number().positive(),
  rssi: Joi.number(),
  snr: Joi.number(),
  latitude: Joi.number(),
  longitude: Joi.number(),
  firmwareVersion: Joi.string().max(20),
  bluetoothMac: Joi.string(),
  wifiMac: Joi.string(),
  lastCheckIn: Joi.date(),
  manufacturerDate: Joi.date(),
  installationDate: Joi.date(),
  errorCode: Joi.string(),
  carrier: Joi.string(),
  signalStrength: Joi.number().integer(),
  propertyId: Joi.number().integer(),
  projectId: Joi.number().integer(),
  zoneId: Joi.number().integer(),
  miscData: Joi.object(),
  thingName: Joi.string(),
  isOnline: Joi.boolean(),
  lnsName: Joi.string(),
  bleName: Joi.string(),
  addedBy: Joi.number().integer(),
  firstNetworkPreference: Joi.string(),
  secondNetworkPreference: Joi.string(),
  thirdNetworkPreference: Joi.string(),
  simPreference: Joi.string(),
  deviceStateChangedAt: Joi.date(),
  messagesReceived: Joi.number().integer(),
  messagesSent: Joi.number().integer(),
  messagesResetDate: Joi.date(),
  isGnssEnabled: Joi.boolean(),
  wifiConfiguration: Joi.object(),
  ethernetConfiguration: Joi.object(),
  cellularConfiguration: Joi.object(),
  state: Joi.string().valid('online', 'offline'),
  networkMode: Joi.string().default('Basics Station'),
  connectionStatus: Joi.string().default('Disabled'),
};

const createGatewaySchema = Joi.object().keys({
  ...common_field,
});
const updateGatewaySchema = Joi.object().keys({
  id: Joi.number().required(),
  ...common_field,
});

module.exports = {
  createGatewaySchema,
  updateGatewaySchema,
};
