const timezonesData = [
  { code: 'GMT', name: 'Greenwich Mean Time', relativeToGmt: 'GMT', visible: false, sequenceName: 15 },
  { code: 'UTC', name: 'Universal Coordinated Time', relativeToGmt: 'GMT', visible: false, sequenceName: 16 },
  { code: 'ECT', name: 'European Central Time', relativeToGmt: 'GMT+1:00', visible: false, sequenceName: 17 },
  { code: 'EET', name: 'Eastern European Time', relativeToGmt: 'GMT+2:00', visible: false, sequenceName: 18 },
  { code: 'ART', name: '(Arabic) Egypt Time', relativeToGmt: 'GMT+2:00', visible: false, sequenceName: 19 },
  { code: 'EAT', name: 'Eastern African Time', relativeToGmt: 'GMT+3:00', visible: false, sequenceName: 20 },
  { code: 'MET', name: 'Middle East Time', relativeToGmt: 'GMT+3:30', visible: false, sequenceName: 21 },
  { code: 'NET', name: 'Near East Time', relativeToGmt: 'GMT+4:00', visible: false, sequenceName: 22 },
  { code: 'PLT', name: 'Pakistan Lahore Time', relativeToGmt: 'GMT+5:00', visible: false, sequenceName: 23 },
  { code: 'IST', name: 'India Time', relativeToGmt: 'GMT+5:30', visible: false, sequenceName: 24 },
  { code: 'BST', name: 'Bangladesh Time', relativeToGmt: 'GMT+6:00', visible: false, sequenceName: 25 },
  { code: 'VST', name: 'Vietnam Time', relativeToGmt: 'GMT+7:00', visible: false, sequenceName: 26 },
  { code: 'CTT', name: 'China Taiwan Time', relativeToGmt: 'GMT+8:00', visible: false, sequenceName: 27 },
  { code: 'JST', name: 'Japan Time', relativeToGmt: 'GMT+9:00', visible: false, sequenceName: 28 },
  { code: 'ACT', name: 'Australia Central Time', relativeToGmt: 'GMT+9:30', visible: false, sequenceName: 29 },
  { code: 'AET', name: 'Australia Eastern Time', relativeToGmt: 'GMT+10:00', visible: false, sequenceName: 30 },
  { code: 'SST', name: 'Solomon Time', relativeToGmt: 'GMT+11:00', visible: false, sequenceName: 31 },
  { code: 'NST', name: 'New Zealand Time', relativeToGmt: 'GMT+12:00', visible: false, sequenceName: 32 },
  { code: 'MIT', name: 'Midway Islands Time', relativeToGmt: 'GMT-11:00', visible: false, sequenceName: 1 },
  { code: 'HT', name: 'Hawaii Time', relativeToGmt: 'GMT-10:00', visible: true, zone: 'America/Adak', sequenceName: 2 },
  { code: 'AT', name: 'Alaska Time', relativeToGmt: 'GMT-9:00', visible: true, zone: 'US/Alaska', sequenceName: 3 },
  { code: 'PT', name: 'Pacific Time', relativeToGmt: 'GMT-8:00', visible: true, zone: 'America/Los_Angeles', sequenceName: 4 },
  { code: 'PNT', name: 'Phoenix Time', relativeToGmt: 'GMT-7:00', visible: false, sequenceName: 5 },
  { code: 'MT', name: 'Mountain Time', relativeToGmt: 'GMT-7:00', visible: true, zone: 'America/Denver', sequenceName: 6 },
  { code: 'CT', name: 'Central Time', relativeToGmt: 'GMT-6:00', visible: true, zone: 'America/Chicago', sequenceName: 7 },
  { code: 'ET', name: 'Eastern Time', relativeToGmt: 'GMT-5:00', visible: true, zone: 'America/New_York', sequenceName: 8 },
  { code: 'IET', name: 'Indiana Eastern Time', relativeToGmt: 'GMT-5:00', visible: false, sequenceName: 9 },
  { code: 'PRT', name: 'Puerto Rico and US Virgin Islands Time', relativeToGmt: 'GMT-4:00', visible: false, sequenceName: 10 },
  { code: 'CNT', name: 'Canada Newfoundland Time', relativeToGmt: 'GMT-3:30', visible: false, sequenceName: 11 },
  { code: 'AGT', name: 'Argentina Time', relativeToGmt: 'GMT-3:00', visible: false, sequenceName: 12 },
  { code: 'BET', name: 'Brazil Eastern Time', relativeToGmt: 'GMT-3:00', visible: false, sequenceName: 13 },
  { code: 'CAT', name: 'Central African Time', relativeToGmt: 'GMT-1:00', visible: false, sequenceName: 14 },
  { code: 'HST', name: 'Hawaii Time', relativeToGmt: 'GMT-10:00', visible: false, zone: 'America/Adak', sequenceName: 33 },
  { code: 'AST', name: 'Alaska Time', relativeToGmt: 'GMT-9:00', visible: false, zone: 'US/Alaska', sequenceName: 34 },
  { code: 'PST', name: 'Pacific Time', relativeToGmt: 'GMT-8:00', visible: false, zone: 'America/Los_Angeles', sequenceName: 35 },
  { code: 'MST', name: 'Mountain Time', relativeToGmt: 'GMT-7:00', visible: false, zone: 'America/Denver', sequenceName: 36 },
  { code: 'CST', name: 'Central Time', relativeToGmt: 'GMT-6:00', visible: false, zone: 'America/Chicago', sequenceName: 37 },
  { code: 'EST', name: 'Eastern Time', relativeToGmt: 'GMT-5:00', visible: false, zone: 'America/New_York', sequenceName: 38 },
];
module.exports = timezonesData;

// https://publib.boulder.ibm.com/tividd/td/TWS/SC32-1274-02/en_US/HTML/SRF_mst273.htm
