module.exports = {
  USER: {
    USER_NOT_EXIST: 'User does not Exist',
    INVALID_PASSWORD: 'Invalid email or password ',
  },
  USER_TYPE: {
    OXIT: 'oxit',
    CLIENT: 'client',
    CUSTOMER: 'customer',
  },
  USER_ROLE: {
    ADMIN: 'administrator',
    CUSTOMER_SERVICE: 'customer_service',
    SALES: 'sales',
    OWNER: 'owner',
    DISTRIBUTOR: 'distributor',
    MANAGER: 'manager',
    READ_ONLY: 'read_only',
    USER: 'user',
  },
  defaultNotificationSettings: {
    PUSH: true,
    EMAIL: true,
    SMS: false,
  },
  userStatus: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
  },
  COMMON_STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
  },

  MESSAGES: {
    INTERNAL_SERVER_ERROR: 'Internal Server Error.',
    INVALID_REQUEST: 'Invalid or incomplete data.',
    INVALID_CREDENTIALS: 'Incorrect Email or password',
    SUCCESSFUL: 'SUCCESSFUL',
    UNAUTHORIZED: 'UnAuthorized! Please Login to continue',
    ENTITY_NOT_FOUND: 'Entity was not found.',
    LIMIT_UNEXPECTED_FILE: 'Invalid Number of files',
    OK: 'OK',
    NOT_FOUND: 'Requested resource not found on server',
    PONG: 'pong',
    FORBIDDEN: 'Request forbidden',
    PERMISSION_DENIED: 'Permission denied',
    USER_CREATED: 'User successfully created',
    EMAILS_ARRAY_REQUIRED: 'Emails array should not be empty',
    USERS_DISABLED: 'Users disabled',
    USERS_ENABLED: 'Users enabled',
    USERS_DELETED: 'Users deleted',
    USER_UPDATED: 'User successfully updated',
    USER_NOT_FOUND: 'User either not found or deleted',
    USER_ALREADY_VERIFIED: 'User already verified',
    RESEND_USER_INVITATION: 'User invitation resent',
    USER_GROUP_CREATED: 'User group created',
    NO_SORT_COLUMN_PROVIDED: 'Provide sort column with sort order',
    FEATURES_LIST: 'Features List.',
    USER_GROUP_UPDATED: 'User Group successfully updated.',
    USER_GROUP_LIST: 'User Groups list.',
    USER_GROUP_DETAILS: 'User Group details.',
    USER_GROUP_DELETED: 'User Group successfully deleted.',
    USER_GROUP_NOT_FOUND: 'User Group either not found or deleted.',
    USER_GROUP_HAS_USER: 'User Group has user so can not be deleted.',
    PROPERTY_CREATED: 'Property created',
    PROPERTY_UPDATED: 'Property successfully updated.',
    PROPERTY_LIST: 'Properties list.',
    PROPERTY_DETAILS: 'Property details.',
    PROPERTY_DELETED: 'Property successfully deleted.',
    PROPERTY_NOT_FOUND: 'Property either not found or deleted.',
    CUSTOMER_CREATED: 'Customer created',
    CUSTOMER_UPDATED: 'CUstomer successfully updated.',
    CUSTOMER_LIST: 'Properties list.',
    CUSTOMER_DETAILS: 'Customer details.',
    CUSTOMER_DELETED: 'Customer successfully deleted.',
    CUSTOMER_NOT_FOUND: 'Customer either not found or deleted.',
    CUSTOMER_COMPANY_ALREADY_EXIST: 'Customer company name already exist.',
    CUSTOMER_OTP_SENT: 'Otp send to customer.',
    OWNER_NOT_FOUND: 'Only owner can perform this action',
    COMPANY_OWNER_TRANSFERRED: 'Company owner transferred successfully',
    CUSTOMER_OTP_VERIFICATION_FAILED: 'Customer otp verification failed',
  },

  // Client text

  CLIENT_MESSAGES: {
    CLIENT_NOT_FOUND: 'Client either not found or deleted',
    CLIENT_CREATED: 'Client created successfully',
    CLIENT_UPDATED: 'Client updated successfully',
    CLIENT_DELETED: 'Client deleted successfully',
    CLIENT_LIST: 'Client list ',
    CLIENT_DETAILS: 'client details',
    CLIENT_DATA_NOT_PROVIDED: 'Client data not provided',
  },

  // Gateway Text
  GATEWAY_MESSAGES: {
    GATEWAY_NOT_FOUND: 'Gateway either not found or deleted',
    GATEWAY_CREATED: 'Gateway created successfully',
    GATEWAY_UPDATED: 'Gateway updated successfully',
    GATEWAY_DELETED: 'Gateway deleted successfully',
    GATEWAY_LIST: 'Gateway list ',
    GATEWAY_DETAILS: 'Gateway details',
    GATEWAY_DATA_NOT_PROVIDED: 'Gateway data not provided',
  },

  // Zones text

  ZONE_STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    DELETED: 'deleted',
  },
  ZONE_MESSAGES: {
    ZONE_CREATED: 'Zone successfully created',
    ZONE_DATA_NOT_PROVIDED: 'Zone Data not provided',
    ZONE_UPDATED: 'Zone successfully updated',
    ZONES_LIST: 'Zones list',
    ZONE_DETAILS: 'Zone details',
    ZONE_DELETED: 'Zone successfully deleted',
    ZONE_NOT_FOUND: 'Zone either not found or deleted',
  },

  /**
   * HTTP Code constants
   */
  HTTP_STATUS: {
    OK: 200,
    NOT_FOUND: 404,
    ERROR: 400,
    UNPROCESSABLE_ENTITY: 422,
  },
  /**
   * Response Header constants
   */
  RES_HEADER: {
    CONTENT_TYPE: 'application/json',
    CHAR_SET: 'utf-8',
  },
  STATUS: {
    ACTIVE: 'active',
    DELETED: 'deleted',
    DISABLED: 'disabled',
  },
  FEATURES: {
    CLIENT: 'client',
    USER: 'user',
    USER_GROUP: 'user_group',
    CUSTOMER_ACCOUNT: 'customer_account',
    TRANSFER_OWNERSHIP: 'transfer_ownership',
    PROPERTY: 'property',
    ZONE: 'zone',
    GATEWAY: 'gateway',
    DEVICE: 'device',
    DEVICE_MODAL: 'device_modal',
    DASHBOARD: 'dashboard',
    ALERT_THRESHOLD: 'alert_threshold',
    NOTIFICATION_SETTING: 'notification_setting',
    FUOTA: 'fuota',
    FIRMWARE: 'firmware',
    LNS_CONFIGURATIONS: 'lns_configurations',
  },
  PERMISSIONS: {
    FULL: 'full_access',
    VIEW: 'view_only',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
  },
  LOGIN: '/#/login',
  BASE_LOGO_URL: 'https://d2l1apd4nho3rf.cloudfront.net/',
  COUNT: 25,
  OFFSET: 0,
  DELETED: 'deleted',
  SLUGNAME: {
    DART_DISPLAYS: 'dart_displays_dart_displays',
    WATERCOP: 'dynaquip_watercop',
    OIS: 'optical_inventory_solutions_optical_inventory_solutions',
    TACO: 'taco_taco',
    ARBOR_ALERT_AATA: 'arbor_alert_aata',
    BEVERAGE_ANALYTICS: 'dynasty_llc_keg_monitoring_platform',
    CROWN_CASTLE: 'crown_castle_international_corp._ccltm',
    OMNI_ID: 'omni-id_inc_oisap',
    ZAK_TRACK: 'zflo_zaktrak',
    NDS: 'next_degree_safety_nds',
    HELIUM: 'helium_oxtech_helium',
    OXTECH_8_CHANNEL: 'oxtech_8_channel_gateway',
    NEW_COSMOS: 'new_cosmos_electric_co_new_cosmos',
  },
};
